server:
  port: '@eureka.server.port@'
eureka:  instance:    hostname: '@eureka.host@' #注册中心IP地址
  client:    service-url:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #注册地址
    register-with-eureka: false #因为自己是注册中心，是否将自己注册给自己的注册中心（集群的时候需要设为true）
    fetch-registry: false        #因为自己是注册中心，不需要检索服务信息spring:  profiles:    active: '@profiles.active@'
  application:    name: tms-eureka-server              